### ISSUE TITLE
Change the CircularProgress loading animation to our own branded one

### ISSUE THREAD

**Issue by barto74** [boxwise/boxwise#106]
## Problem
The CircularProgress component of material-ui is boring.
Additionally, ff you log in the loading circle is not centered yet.

## Solution
We created our own branded animation.
You can find it in /public/images/loading-boxes.gif
Exchange the material-ui circle with our branded one.

**Comment by HaGuesto** [comment]
@barto74 could this be a design task fo the Hackathon?

**Comment by barto74** [comment]
@HaGuesto this is not a design task, but an implementation task

**Comment by HaGuesto** [comment]
Still one for the Hackathon? Sounds like a good first issue.

**Comment by sfetiveau-ta** [comment]
I'll take this.

**Comment by bfirsh** [comment]
Related: there are lots of places the loading spinner is used where it is not centred, etc. The component for the spinner should probably know how to centre itself in whatever its parent is.

**Comment by bfirsh** [comment]
The notable one is the loading spinner when you first open the app that's jammed up in the top-left corner...

**Comment by sfetiveau-ta** [comment]
It was my first React component. I only added support for size and className, that were already used in the code. See merge request.
