### ISSUE TITLE
Link back to home page from create organization page

### ISSUE THREAD

**Issue by barto74** [boxwise/boxwise#107]
## Problem

There is no link if you sign up to go back to the home page when we ask to name the orgaization, so users will get stuck on it if the don't intend to complete the process.

## Proposed solution

Add a link to return back to the home page.

**Comment by HaGuesto** [comment]
@barto74 I do not fully understand this problem.

**Comment by bfirsh** [comment]
@HaGuesto I wrote this sorry. I’ve clarified. It also depends on #150

**Comment by DeveloperDavo** [comment]
I am happy to work on this.  Is there any preference for the design?

**Comment by HaGuesto** [comment]
Hey @DeveloperDavo, yes great! In #191 the color and font of our visual identity.

**Comment by DeveloperDavo** [comment]
Just sumbitted https://github.com/boxwise/boxwise/pull/288 :)
