### ISSUE TITLE
Make human IDs unique

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxwise#119]
I spent some thought on this topic the last days. Sorry that my first discription was not clear.
### I would propose the following workflow for a unique human ID creation:
1. When an organization signs up they should be asked "How many locations/piles do you need?" and "Up to how many boxes can be stored in one location? (As a rule of thumb we recommend 30-40)".
2. In our database we create create a locations collection. Each location document should include the following attributes: ID, total capacity, free capacity, lowest free spot, (description, reserrved for category)
3. A UI for locations should be created to update the total capacity (and/or description). A overview of Boxes in a certain location might be neat.
4. When a volunteer makes a box, the human ID is generated as follows:
- A location is randomly choosen (inbetween the locations allowed for its category)  with a distribution corresponding to the free capacity, e.g. if location 1 contains already 10 boxes more than location 2 than it is more probable that location 2 is chosen.
- The number of the chosen location are the first digits of the human ID.
- The last digits of the human ID is the lowest free spot number in a certain pile.
- The box is assigned his human ID and the location data needs to be updated.

### Here two examples for the human ID generation:
- Warehouse BoxHouse has 25 different piles in their warehouse. Each one can contain 30 boxes.
A volunteer creates the first box. Pile 14 is randomly chosen. Since all piles are empty the lowest free spot is number 01. The human ID of the first box is 1401.
- Warehouse BoxHouse has succesfully used Boxwise for some time and did some deliveries already.
A volunteer creates a box. Pile 14 is randomly chosen. Pile 14 is half full. However, the lowest free spot in that pile is 5 since recently box 1405 was ordered and delivered. The human ID for the box is 1405.

### General
- The human ID is a reference to a specific location in your warehouse rather than a unique ID.
- The user should be able to change the human ID of a box.
### Pros
- You know that you only have to draw one random number to create a unique human ID. (With the current method you draw a number and then have tocheck if it already exists.)
- You know when a pile/location is full (and when your warehouse is over capacity.)
- If a location is a shelf and not a pile, boxes are always put at empty slots. Boxes do not have to be moved around in a pile that often.
- If a box got lost in the system (The box is still there, but its space/slot is freed in the App.) and a new box is generated to the slot of the lost box, then the lost box is found again. 
### Cons
- You need to save all the location data and update it during the process.
- If two people create boxes offline at the same time, the probability of creating the same human ID twice is quite high - 1/(number of locations). However, if both want to place their item at the same slot they would recognize that.

**Comment by barto74** [comment]
What does that help us with? See also the discussion in #96

**Comment by barto74** [comment]
I'm also thinking: i like to have numbers that are not ascending, because that generates numbers that are almost the same. Like 728534 and 728543. This is likely going to confuse people, because those boxes are in the same stack as well. 
I would rather propose to use a [check digit](https://en.wikipedia.org/wiki/Check_digit) to prevent this.

**Comment by bfirsh** [comment]
(BTW I have renamed box numbers to "human IDs", so I will use that terminology here.)

I think this is confusing a bunch of issues. The requirements are:

1) Human IDs need to be unique within an organization.
2) They need to be generated offline, somehow. (Or, have a reasonable chance of not colliding when offline.)

This is a complicated problem (see my comment in #117) so I'm not thinking about it until after the MVP. :)

**Comment by HaGuesto** [comment]
@barto74 @bfirsh 
I spent some thought on this topic the last days. Sorry that my first discription was not clear.
### I would propose the following workflow for a unique ID creation:
1. When an organization signs up they should be asked "How many locations/piles do you need?" and "Up to how many boxes can be stored in one location? (As a rule of thumb we recommend 30-40)".
2. In our database we create create a locations collection. Each location document should include the following attributes: ID, total capacity, free capacity, lowest free spot, (description, reserrved for category)
3. A UI for locations should be created to update the total capacity (and/or description). A overview of Boxes in a certain location might be neat.
4. When a volunteer makes a box, the human ID is generated as follows:
- A location is randomly choosen (inbetween the locations allowed for its category)  with a distribution corresponding to the free capacity, e.g. if location 1 contains already 10 boxes more than location 2 than it is more probable that location 2 is chosen.
- The number of the chosen location are the first digits of the human ID.
- The last digits of the human ID is the lowest free spot number in a certain pile.
- The box is assigned his human ID and the location data needs to be updated.

### Here two examples for the human ID generation:
- Warehouse BoxHouse has 25 different piles in their warehouse. Each one can contain 30 boxes.
A volunteer creates the first box. Pile 14 is randomly chosen. Since all piles are empty the lowest free spot is number 01. The human ID of the first box is 1401.
- Warehouse BoxHouse has succesfully used Boxwise for some time and did some deliveries already.
A volunteer creates a box. Pile 14 is randomly chosen. Pile 14 is half full. However, the lowest free spot in that pile is 5 since recently box 1405 was ordered and delivered. The human ID for the box is 1405.

## Remarks:
### General
- The human ID is a reference to a specific location in your warehouse rather than a unique ID.
- The user should be able to change the human ID of a box.
### Pros
- You know that you only have to draw one random number to create a unique human ID. (With the current method you draw a number and then have tocheck if it already exists.)
- You know when a pile/location is full (and when your warehouse is over capacity.)
- If a location is a shelf and not a pile, boxes are always put at empty slots. Boxes do not have to be moved around in a pile that often.
- If a box got lost in the system (The box is still there, but its space/slot is freed in the App.) and a new box is generated to the slot of the lost box, then the lost box is found again. 
### Cons
- You need to save all the location data and update it during the process.
- If two people create boxes offline at the same time, the probability of creating the same human ID twice is quite high - 1/(number of locations). However, if both want to place their item at the same slot they would recognize that.

**Comment by barto74** [comment]
1. I think we should ask people about the warehouse size (in square meters) and from there give them the amount of piles and amount of boxes as an indication. And that should be overridable - because we can't be exact. 
2. I still don't like sequential box numbers for reasons given before.
3. It sounds in general quite complicated what you propose and I don't see which real problems it solves. We can't be this exact. I have examples where the stacks are not exactly same sized (vincentes, athens wh of drops). And boxes are varying from big to small.

**Comment by HaGuesto** [comment]
replying to your comments:
about 1.)
That's a quite nice idea. It reduces it to one step in the registration.
A location UI should be added, too. I think I mentioned it already.
about 2.)
I get your point, but I cannot imagine an example where it should really be a problem as long as the numbers are generated by us and only 4 digits long. Do you mean it is harder to find a box?
about 3.)
The random selection of a pile sounds maybe quite complicated in my description, but it is not. 
We can start with just drawing one pile from all with equal probabilities which is the same as we do now.
The last digits of the number are a bit more work since you have to keep track of all the piles and they need to be updated all the time. However, I think it is worth it du to the pros I mentioned before.

The idea for the the latter digits of the box number is coming from our logistic students, a friend of mine who works in a library and my experience in Nea Kavala:
- The students asked why the number has so many digits and only the first two numbers are used. Also, why does the box number have to be unique if our database ID is already unique?
- In libraries a similar system is used. Books are first stored by their category and maybe a letter or two taken from their author or title, but after that the number is drawn ascendingly.
- During my time in Nea Kavala, it would have been nice to get a warning that the WH capacity is reached. The piles were sometimes 2 meters tall. Volunteers / coordinators would maybe have thought of allocating new space or how they could get rid of stuff if the system would have warned them.
