### ISSUE TITLE
Hide URL bar on iOS

### ISSUE THREAD

**Issue by bfirsh** [boxwise/boxwise#122]
I can't remember if this is possible while also retaining native scroll, but worth investigating.

**Comment by barto74** [comment]
There used to be a simple trick with a line of javascript, but that is not working anymore. Solutions now seem to be rather difficult and many people regard this undesirable.
For example: https://stackoverflow.com/questions/24889100/ios-8-removed-minimal-ui-viewport-property-are-there-other-soft-fullscreen

**Comment by HaGuesto** [comment]
I'm in favor if removing the URL line. The less options our user has the better.

**Comment by bfirsh** [comment]
I'd say forget about it. It's mostly mitigated by #148, which is clearly the approach iOS wishes us to take.
