### ISSUE TITLE
Setup a dummy marketing page

### ISSUE THREAD

**Issue by barto74** [boxwise/boxwise#124]
So that users that are not logged in arrive at a marketing page (which will be filled later) that can contain a login button.

**Comment by HaGuesto** [comment]
@barto74 Could this be a Design task for the Hackathon?

**Comment by barto74** [comment]
@HaGuesto i created a simple dummy, but they can work on something better, maybe inspired by the wireframe that i made weeks ago.

**Comment by HaGuesto** [comment]
Would you like to write that issue for them?
