### ISSUE TITLE
Add names to users

### ISSUE THREAD

**Issue by bfirsh** [boxwise/boxwise#125]
## Problem

At the moment users are just emails, but it would be nice if there were real names so we could say who created boxes and so on.

## Proposed solution

When you sign up (both creating an organization and via invite), it should ask for your name. This should be stored on your profile.

Your name should be displayed in the menu instead of your email. If they are missing a name, just display their email.

## Future

At some point we should add a way of changing your name, so users without one can set one.

**Comment by AveryVine** [comment]
This can be marked as resolved!

**Comment by bfirsh** [comment]
wahey, thanks @AveryVine!
