### ISSUE TITLE
Write better security rules for creating/joining organizations

### ISSUE THREAD

**Issue by bfirsh** [boxwise/boxwise#132]
We currently assume that organization IDs are secret, which is not a thing we should assume. We should be clever and only allow you to create profiles if you also have an invite for the organization (probably by setting an `invitedFrom` field on profiles).

If you want to help with this, there is a test suite in `src/__tests__/firestore.rules.test.js`. Instructions on how to set it up is in the readme.

**Comment by bfirsh** [comment]
Note to tripadvisor people - there is a test suite for this in `src/__tests__/firestore.rules.test.js`. Instructions on how to set them up is in the readme.

**Comment by HaGuesto** [comment]
Closed ("Paused") due to discussion #275.
