### ISSUE TITLE
When using "add to home screen" on iOS, you can’t get out of label page

### ISSUE THREAD

**Issue by barto74** [boxwise/boxwise#136]
It should open in a new window, or have a back button that is not printed. 
Anyway we should do it in pdf in the future

**Comment by bfirsh** [comment]
To clarify: this is when you add the app to your homescreen iOS, with the share menu at the bottom of Mobile Safari.

**Comment by barto74** [comment]
I think a quick fix for now is to make an overlay that gives the option to go back to the dashboard page.
I didn't see a way to link to Safari, also I wouldn't expect people to print QR-labels from their mobile, but from a desktop.
