### ISSUE TITLE
Write down a bunch of good first issues

### ISSUE THREAD

**Issue by bfirsh** [boxwise/boxwise#145]
This is in particular for a hack day in a couple of weeks, but would be a useful thing to have anyway.

- Easy bugs to fix
- Simple features to add
- Self-contained design things (e.g. icons)
- Writing unit tests
- Writing browser tests
- Documentation
- Landing page improvements/feedback
- Pie in the sky future ideas we could do with prototypes for

https://github.com/boxwise/boxwise/labels/good%20first%20issue

**Comment by bfirsh** [comment]
I've made lots of things here: https://github.com/boxwise/boxwise/labels/good%20first%20issue

Still missing some design things, and perhaps pie in the sky prototype ideas.

**Comment by HaGuesto** [comment]
@bfirsh What do you mean by pie in the sky?

**Comment by bfirsh** [comment]
@HaGuesto @barto74 Some more good things for the hack day would be a few simple features to add. Have you got any ideas for things that might be useful for IHA?

**Comment by barto74** [comment]
Could they start setting up the box ordering flow?

**Comment by bfirsh** [comment]
Potentially, yeah! If we have some wire frames we could create well-specified issues for a couple of screens. If there is an unusual bit of UI, perhaps we could create an issue to make a component for that bit of UI.

**Comment by bfirsh** [comment]
I think we've done a good job of this. :)
