### ISSUE TITLE
Style form errors

### ISSUE THREAD

**Issue by bfirsh** [boxwise/boxwise#156]
## Problem

Global form errors are not styled at the moment.

## Proposed solution

In most of the forms, there is a bit of code that looks like this at the top:

```
{/* TODO: style errors */}
        {errors.form ? (
          <Typography variant="body1">{errors.form}</Typography>
        ) : null}
```

`errors.form` is set in the submit handler if the Firebase API returns an error.

This should be styled somehow. Perhaps in red, with something to set it apart from the rest of the form. Material-UI might have a component we can use for this.

**Comment by stella-wang** [comment]
TA on it.

**Comment by jamescrowley** [comment]
Suggest we use FormHelperText with the 'error' flag set to true.
