### ISSUE TITLE
Refactor SignInForm to use a container component

### ISSUE THREAD

**Issue by bfirsh** [boxwise/boxwise#158]
## Problem

All the presentation and logic is muddled in the same file.

## Solution

Split it out into `SignInForm` and `SignInFormContainer`, using a property for the Formik submit handler. See the other containers components for examples of how this is done.

**Comment by rubenspgcavalcante** [comment]
Hey @bfirsh , I can take a look into that 👍

**Comment by rubenspgcavalcante** [comment]
I have something unrelated to the issue but is about the sign-in too.
Checking the code here, the best way to handle the sign in is to integrate it to the `react-router` and mark all pages (within the components metadata or a routing file) to say that page is only accessible after authentication. So every route change should check that using the store as reference, redirecting the user to the signin route if the user data isn't present on the app state.
Should I open an issue referring to this?

**Comment by rubenspgcavalcante** [comment]
Normally the user information should go to a inner state like `user.info` or `user.data`, etc.
This makes easy to handle what actually coming from the database and what is from the app itself, like is the user is being loaded `user.loading` or if had some auth. error `user.error`.
This way is easy to check even if the user is not authenticated, like `if( !user.data) ...`.

Should I go for this refactor and if so, can you point me out were do we use this info?
Thanks!

**Comment by bfirsh** [comment]
Sure! You mean just in this component, or the user in the Redux state?

**Comment by rubenspgcavalcante** [comment]
On the redux state. I've saw something similar on the profile state too, but got no time to work on it :(
