### ISSUE TITLE
deploy firestore in README

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxwise#174]
I think the command in README to deploy new firestore rules should be

`yarn run firebase deploy --only firestore:rules`

Am I right @bfirsh ?

**Comment by bfirsh** [comment]
Nope. It also needs to deploy indexes now.

If you're curious as to how the `yarn run deploy-firestore` command works: custom commands for `yarn run` are defined in `package.json`, under the `scripts` section.

There you can see what it's doing. It is almost what you suggest, but without the `:rules` specifier, so it also deploys the indexes.
