### ISSUE TITLE
Show the number of items in ProductPage

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxwise#178]
Show a number of items in the "manage Products" menu. 

## Possible solutions
1. Save the number of items as attribute of a product and update it when a new box is created, edited or deleted. Do not forget to implement a data migration to not forget the boxes who are already registered.
2. Query over all boxes with a certain product in it and sum up the number of items.

## Future
In the long run, the first solution is probably preferable.

**Comment by bourds** [comment]
Looking at this one (from TA)

**Comment by bourds** [comment]
So to do it the 'right' way https://github.com/boxwise/boxwise/issues/214 is going to be a prerequisite.
