### ISSUE TITLE
When logged in, there is a flash of sign in page on first load

### ISSUE THREAD

**Issue by bfirsh** [boxwise/boxwise#181]
## Steps to reproduce

1) Sign in
2) Open a new tab, open boxwise

## Expected

A loading indicator is displayed, then I land on dashboard.

## What actually happened

The sign in page displayed for a second, then a loading indicator displayed, then I landed on the dashboard.

Probably related to #161

**Comment by HaGuesto** [comment]
The `AuthedRoute` component is broken.
It always redirects to the `SignInPage` which in turn redirects to the Dashoard.
The first redirect should not happen.

**Comment by mtimmerm** [comment]
The AuthedRoute component is fine, but authentication doesn't happen immediately.  The App is initially rendered in the unauthenticated state, and the authentication response comes in from Firebase a little later, after the user has been redirected to /home.

Since there can be a noticeable delay in receiving auth, it is appropriate to render the app in an unauthenticated state initially, but there should be a reasonable transition to the dashboard when the auth state changes.

**Comment by bfirsh** [comment]
The way this originally worked is the initial state for user was `loading: true` (in `src/reducers/user.js`). Then, when the initial `onAuthStateChanged` is fired, it sets it to `loading: false`. That is the correct solution, I think.

@rubenspgcavalcante You refactored this - do you have any opinions about this? Was there a particular reason `loading: false` is the initial state?

**Comment by rubenspgcavalcante** [comment]
Putting loading to true can bring problems in the future on pages that **doesn't request authentication**. AuthedRoute should be the one responsible to check if there's no user information, on pages which requests the used being logged, wait for something like the action promise or so, and only then take the action of redirecting the user to the login page or not. Currently I think it just checks if is the user is null then redirects.
Anyway, need to check further on that :)

**Comment by bfirsh** [comment]
Presumably if a page doesn't need authentication, you just don't put AuthedRoute in front of it? Then a loading indicator doesn't display. I don't understand why that is a problem.

The initial state is that the logged in state is unknown and is waiting for `onAuthStateChanged` to indicate whether they are logged in or not. It seems semantically correct that it is "loading" during that time.

**Comment by rubenspgcavalcante** [comment]
> It seems semantically correct that it is "loading" during that time.

Sorry, can't agree as in the case of the page don't have the AuthedRoute, the state shouldn't be `loading: true` as isn't loading any user.
The AuthedRoute should be the one to trigger the user loading action (making the state `loading: true`). The state should start `null` so we know any action was triggered before. Only when `loading` is **actually** false it should take some action over this (redirect to login if failed, redirect to dashboard or last route if true).

**Comment by rubenspgcavalcante** [comment]
Ok, I'll work on that. 
As the component is doing two jobs (routing and auth checking) first detach the route from within it and connect it to the necessary state/actions to do the job. We should use it as a HOC, so we can test it with and without authentication, and pass it to the `Route` component.
