### ISSUE TITLE
Design six-eight icons/animations for the landing page

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxwise#185]
In the [website sketch](https://github.com/boxwise/boxwise/files/2116114/Website.sketch.pdf) of #184 the functionality of Boxwise is split up into 6 features - Stock, Distribution, Moving, Forecast, Other services, Mobile phones. 
It would be great to have an icon or animation for each of these tags.

Additionally, an icon depicting that we are an open source project and one that we are trying to empower young (refugee/socially disadvantaged) coders could also be useful. 
Be creative! :)

**Comment by bre-ta** [comment]
Currently working on the "Mobile" icon: "Everything works on your
smartphone, tablet or laptop."
