### ISSUE TITLE
Make app translatable

### ISSUE THREAD

**Issue by bfirsh** [boxwise/boxwise#196]
## Problem

At some point we want to translate the app into other languages. For example, all the NGOs that @barto74 visited in Paris run in French.

If we start making strings translatable now, it will be much less painful to translate in the future.

## Suggested solution

We can use [react-intl](https://github.com/yahoo/react-intl) (highly recommended by @rubenspgcavalcante) to start making strings in the app translatable. We could wrap everything that needs to be translated in `<FormattedMessage>`.

I would suggest we don't start adding translations at this stage. They'll only break and slow us down while the app is changing quickly.

## See also

https://github.com/boxwise/boxwise/issues/52

**Comment by jclarkin** [comment]
I'll take a stab at this (no promises ;))

**Comment by bfirsh** [comment]
#218 sets up the framework for translating and makes dashboard translatable. Thanks @jclarkin!

Making all the other pages translatable is still up for grabs. ;)
