### ISSUE TITLE
Document installing watchmen if `yarn test` runs out of open files

### ISSUE THREAD

**Issue by bfirsh** [boxwise/boxwise#210]
We're running into this with `yarn test` on OS X: https://github.com/facebook/create-react-app/issues/4540

We should doucment that you need to install watchman if you run into this issue. `brew install watchman`

**Comment by vivianlink** [comment]
https://github.com/boxwise/boxwise/pull/270

**Comment by bfirsh** [comment]
Nice thank you @vivianlink!
