### ISSUE TITLE
Detach Container, Component and firebase logic from ProductTable

### ISSUE THREAD

**Issue by rubenspgcavalcante** [boxwise/boxwise#214]
Currently the component `ProductTableContainer` have the three responsibilities.
- First needs to be created a redux container and remove the connect from the component
- Create a private factory method to create the dumb component (currently on `ProductTable`)
- Rename the `ProductTableContainer` for just `ProductTable`
- Detach the firestore query and turn it into a thunk
- Use PureComponent instead of Component (pls!)

A similar approach was taken on the `AddBox` component. Any doubts, check the implementation :)

**Comment by bourds** [comment]
Going to start looking at this one (TA)

**Comment by HaGuesto** [comment]
#261
