### ISSUE TITLE
Change password

### ISSUE THREAD

**Issue by bfirsh** [boxwise/boxwise#23]
There should be a form that allows users to change their password. It could be linked to just above the "Sign out" link in the menu.

You'll want to use this API method: https://firebase.google.com/docs/auth/web/manage-users#set_a_users_password

**Comment by maoning** [comment]
Picking this up :)

**Comment by maoning** [comment]
Is there a preference between reset password through the app and through a password reset email?

**Comment by bfirsh** [comment]
See also #22 :)

This is for a form to change your password, once you are signed in. It could also be the page where you change your email too, and so on, but that seems less essential than changing your password.
