### ISSUE TITLE
Password field is locked when input was invalid

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxwise#280]
## Reproduce
1. Go to the login page of boxwise.
2. Enter a wrong password.

## Problem
The password field is locked and never resolved.

**Comment by dazyoung** [comment]
All input fields are disabled on an failed submission of the form. This can also be seen on the password reset screen.

**Comment by jamescrowley** [comment]
This has been fixed by https://github.com/boxwise/boxwise/pull/463 and previous removals of Formik
