### ISSUE TITLE
Redesign Dashboard

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxwise#282]
The dashboard page needs to be redesigned.
The buttons are too small on mobiles. The position on the screen is not centered. We need some creative and good UI here.

![bildschirmfoto vom 2018-07-03 09-07-46](https://user-images.githubusercontent.com/29065125/42203966-a8442698-7ea0-11e8-940b-8e3a1d4bee96.png)

@barto74 any comments?

**Comment by etiennebaque** [comment]
Hi @HaGuesto. I'm trying to help out on this project, and I'm checking out the issues labelled "Good first issue".

About this issue, what about using Bootstrap? (https://getbootstrap.com/). I can try to implement it and see what I can do with it.

**Comment by barto74** [comment]
Hi @etiennebaque,
Bootstrap is a very nice library to easily create UI elements. In this project we use the Material UI, a library that does a similar thing, especially made for React and it implements Google Material Design.
But just as with Bootstrap, that needs some work in setting up and interface using the right elements from those libraries.
I have done many projects with Bootstrap in the past, I like it. But in this React project we have decided to for Material UI instead. If you feel like, i would like to invite you to take a look at [Material UI](https://material-ui.com) and see if you can help improving our interface using that framework.
Feel free to ask questions here. In issue #191 I have posted a UX sketch, drafting how the application should look like. Feel free to comment on that as well!

**Comment by etiennebaque** [comment]
Hi @barto74,
Thanks very much for your message and for giving me some directions. I don't know React, but I checked out the Material UI documentation as well as the UX sketch, and I managed to get started.
I'll send out a PR whenever I can.

**Comment by HaGuesto** [comment]
Great @etiennebaque! Looking forward to see it! 
Thanks @barto74 for jumping in! :)

**Comment by barto74** [comment]
@etiennebaque i'm here if you want to discuss UX and aesthetics - and the others here can help you if you have more technical struggles. And i'm looking forward to see your contributions!

**Comment by etiennebaque** [comment]
@barto74 and @HaGuesto: I created a new PR #306, which focuses on the app drawer and the navigation bar. Please give it a review whenever you have some time. Thanks!

**Comment by HaGuesto** [comment]
@jamescrowley I think we should close this issue and discuss next meeting how our menu should look like.

I created a new issue for it #505
