### ISSUE TITLE
Convert the project to Webpack 4

### ISSUE THREAD

**Issue by rubenspgcavalcante** [boxwise/boxwise#287]
So, again I want to raise this discussion as it is really important for the future of the project.
While implementing the qr-code reader feature I'm facing to some problems with the compilation of a library which doesn't comes pre-compiled. There's a work around of we compile it by ourselves by just saying to webpack include this lib directory and include it on the babel-loader process.
Here's the problem, we're currently using another lib just to make customisations on the Webpack configuration, but the lib is unable to locate some essential stuff like the babel-loader (packed inside the CRA).
I have another points to why we should not use it anymore:
 - CRA is bundler agnostic, someday they can simply go for another tool like [rollup](https://rollupjs.org/guide/en) or so and as we didn't ejected the config, we will be frozen in a specific version. Of course this scenario is hard to happen, but already shows the problems of using something generic to do a more specific job.
- We're always behind the latest Webpack (and the other tools included) version. Webpack 4 is really easy being capable to run without configuration file, and with a lot of good features as better minification and tree shaking. We should think on that too :)
- We already using a Webpack configuration to make custom stuff, so why not just go for pure Webpack?
- In the future we may want to use SASS, SVGO loaders, Webpack dashboard and bundle analyser plugins and other stuff not included on CRA (more webpack specific configuration...)

So on my view, CRA is good for hot-apps, prototypes and everything that needs to be made fast, but on long term brings complications. What is your opinions on that?

**Comment by HaGuesto** [comment]
We decided in a recent [skype call](https://docs.google.com/document/d/11Fnnn7QL0KoACNxbP2Newd51daHgZxpRzxMWbIKpCSc/edit?usp=sharing) to move to webpack. 
@rubenspgcavalcante should we write a new issue for the refactoring? Could you do that?

**Comment by jamescrowley** [comment]
I'm closing this for now, until CRA actually blocks us doing anything on the revised roadmap. Will look again when we come to the QR Code scanning.
