### ISSUE TITLE
If you're signed in as a user without a profile, it is impossible to sign out

### ISSUE THREAD

**Issue by bfirsh** [boxwise/boxwise#291]
The sign up process can fail half way, resulting in a user with no profile. The site then fails to load, so there is no sign out button to click!

These accounts are completely broken because they aren't associated with organizations, so we should probably display a helpful error message and sign them out.

**Comment by jamescrowley** [comment]
@HaGuesto do you remember how to reproduce this? I haven't been able to - maybe the sign up workflow changed?

**Comment by jamescrowley** [comment]
Closing as can no longer reproduce.
