### ISSUE TITLE
How to keep track of warehouse quality?

### ISSUE THREAD

**Issue by barto74** [boxwise/boxwise#33]
When you look for boxes, sometimes they're unfindable. We have to design our dropapp to minimise the amount of boxes getting lost. If a certain percentage of the boxes that users look for are not being found, dropapp could advice to run an inventory.
(an inventory in the old dropapp was made by marking all boxes in the warehouse as 'lost' and scanning all QR codes to move them back into the warehouse).

**Comment by HaGuesto** [comment]
please check out #119
