### ISSUE TITLE
Remove react-app-rewired

### ISSUE THREAD

**Issue by jamescrowley** [boxwise/boxwise#393]
Owner of react-app-rewired states:

"As of Create React App 2.0 this repo is "lightly" maintained mostly by the community at this point.
Note: I personally use next.js or Razzle which both support custom Webpack out of the box."

Suggest we evaluate replacing with next.js or Razzle, or just adopting Webpack 4 directly as suggested by @rubenspgcavalcante

**Comment by rubenspgcavalcante** [comment]
This was one of the thing I forgot to discuss on the meeting, I think we should get rid of create-react-app on the rewrite/refactor. It's a excellent tool, for prototypes and MVPs, but when the project grows a little it start to give too much headache. Plus CRA add tons of unnecessary dependency like react-native (just check the generated webpack config, it's a mess).
Webpack v4 already gives the possibility to use it with you a zero config, so why not using it :)

**Comment by rubenspgcavalcante** [comment]
Ah just realized, the project will be SSR? If so, it's good to plan the integration with the REST API. A monorepo sounds good for this. One package for the API another for SSR, the server requiring the API. Remember that next.js is a mix of SSR and SPA, just the first render is on the server, all the request it's required to have the REST server to fetch the data. Never used razzle thou

**Comment by jamescrowley** [comment]
@rubenspgcavalcante not sure on SSR yet, only suggested next.js and Razzle on the basis the owner of react-app-rewired states:

"As of Create React App 2.0 this repo is "lightly" maintained mostly by the community at this point.
Note: I personally use next.js or Razzle which both support custom Webpack out of the box."
