### ISSUE TITLE
Set up code coverage tracking

### ISSUE THREAD

**Issue by jamescrowley** [boxwise/boxwise#414]
Using Codecov? Will need to push from Travis CI

**Comment by DurkoMatko** [comment]
there already is a `.travis.yml` file in the repo...seems it runs tests and builds/deploys master to boxwise-production...I'm not sure what should be changed here

**Comment by jamescrowley** [comment]
@DurkoMatko we run the tests & builds automatically - however, code coverage tells you what % of code is actually covered by tests - so it's useful to spot gaps in the code base that are not being tested sufficiently. To do that we need to do two things:

1. Run Yarn with coverage mode turned on
2. Upload the results to codecov
3. (Nice to have) Add the code coverage badge to our readme, to link through to the code coverage results.

You'd do this as part of the Travis CI build (so .travis.yml is exactly the right place to be looking).

https://github.com/codecov/example-node has some examples, but let me know if it's not clear :)

**Comment by DurkoMatko** [comment]
I don't have write rights for this repo so I can't setup codecov. I've set it up on my own fork. Can you check it if it's what you meant should be done? (Test coverage reports are generated and uploaded to codecov + added the badge)

Here the commit: https://github.com/DurkoMatko/boxwise/commit/086b09f45fcaf56c848bb778d76e433fbe0b6c02

**Comment by jamescrowley** [comment]
@DurkoMatko great 👍 Just to record here as already discussed, we'll encrypt the cc token using Travis, as it's not safe to push the cc_token (https://docs.travis-ci.com/user/environment-variables#encrypting-environment-variables)
