### ISSUE TITLE
[Epic] Box ordering

### ISSUE THREAD

**Issue by bfirsh** [boxwise/boxwise#49]
Customers should be able to order products from a warehouse.

## User stories

...

## Wireframes

By @barto74 from #30 

![40649640-1a6c150a-633a-11e8-8e9e-3c2daacf63ca](https://user-images.githubusercontent.com/40906/40707342-17285812-63f9-11e8-8181-3453e058c98c.png)

Watch a clickable demo of this process here: https://xd.adobe.com/view/316e96b8-93d5-438e-5c3f-2d5216f7d4f3-475f/
The clickable demo allows commenting on a screen by screen basis

**Comment by HaGuesto** [comment]
@barto74 Frame 9. I would not add any prediction of the time for delivery.

**Comment by HaGuesto** [comment]
@barto74 frame 11. The colorful dots should contain some information what they stand for.

**Comment by barto74** [comment]
To edit the texts throughout the application: #52

**Comment by HaGuesto** [comment]
@barto74 very useful would be a qr code on the printed packing list / delivery note to move all boxes in the order outside the warehouse.
I think you already added it at the main diagramm.

**Comment by barto74** [comment]
@HaGuesto I think to be generic, we should not distinguish. So 'man' or 'food' is both a category in my examples. Which from my personal experience makes sense, but it is up to the user/organization to decide what the categories are. 
Also considering sizing/aging, i would consider that an attribute of the box, no matter what is actually inside. For a man's t-shirt this attribute can be 'S/M/L', for a kid's shirt it can be age groups and maybe for sun screen it is the blocking factor. 
Regarding age groups: this is not a filter, but actually a sizing. A T-shirt boy 6-8yr is not a product that is restricted to that age-group, it just indicates the size. If the boy grows faster, he gets a 9-12 shirt.
So maybe in the first phases, we can just say that we have categories, that contain products and that product has one attribute to indicate different versions of the product.

**Comment by HaGuesto** [comment]
@barto74 generic is good and I agree that the user should decide what his category and products are.
About the attribute: The workflow you describe sounds like a comment field where you sepecify additional information. 
If you want to limit what you can put in as a attribute depending on what product it is, then there must be a complete new structure for the user where he can define that (like a sizes interface). For now it is to complicated and depending on the demands of the user we might have to introduce a similar feature in the future.
