### ISSUE TITLE
Make a way to easily edit/translate texts throughout the application

### ISSUE THREAD

**Issue by barto74** [boxwise/boxwise#52]
For example by putting all texts in a database, and make an interface for them. Maybe this could also in future be used to become multilingual.

**Comment by HaGuesto** [comment]
@rubenspgcavalcante

**Comment by bfirsh** [comment]
If we specify this more clearly, with suggested technology, it would be a good project for Tripadvisor.

**Comment by rubenspgcavalcante** [comment]
I think there's no need to put on a Database. We have some options that make it more simple for non-tech contributors:

- Go for an ultra simple solution. Create a i18n directory and commit directly the .json files containing the translations. (I think is only a good idea if we're in a rush)

- Create a translations repository, where we can put as a (per)dependency of boxwise (npm module). Although still somehow tech related solution, GitHub turns it easy to edit, commit and create PRs directly without going out of the platform (plus we can control the i18n versions with the npm).

- Use a localisation/translation manager, for instance [POEditor](https://poeditor.com/pricing/).
This is the best solution for non-tech contributors as it have a nice dashboard (easy to create and edit translations). It have a free plan (1000 strings) and we can make a setup similar to what we do with firebase. We can abstract the API on the code level to free the app of the lock vendor.

For the code part:
I strongly tend to use [react-intl](https://github.com/yahoo/react-intl) for all my projects as it covers all my requirements. This is just a personal preference tho, I'm open to hear from you other alternatives :)

**Comment by bfirsh** [comment]
:+1:

To clarify for the hack day: a good task would be to wrap all strings in the app with react-intl's `FormattedMessage`.

That will allow us to translate at some point in the future, when we need to. We probably shouldn't translate anything at this stage, because it'll just change and break.

**Comment by bfirsh** [comment]
Summarised in #196
