### ISSUE TITLE
How to send a nicely formatted page with a pick list, directly from Boxwise to a printer

### ISSUE THREAD

**Issue by barto74** [boxwise/boxwise#56]
The user that triggers the print, has a mobile phone that is not connected to this printer, but ideally a packing list ends up in a printer somewhere at the moment he finished picking an order.
The packing list contains all the boxes packed, the destination and a qr-code that redirects to a page to confirm giving out the order to the customer.

**Comment by HaGuesto** [comment]
### Question for tripAdvisor HackDay
In one of our warehouse processes it would be great if a user could directly print something similar to a delivery note, e.g. when they picked an order in their warehouse.
What Hardware would you need? How could a Print-Button inside Boxwise work?
