### ISSUE TITLE
Prepare for TripAdvisor Hackathon

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxwise#58]
What do we need to prepare for the Hackathon with trip Advisor on the 20th of June?
Feel free to add change this issue.

- [x] create template for clear self-contained issues @bfirsh #80 
- [x] write first issue examples @bfirsh #145 
- [x] create some design tasks
- [x] create some questions
- [x] create a survey
- [x] presentation

**Comment by bfirsh** [comment]
done done done :)
