### ISSUE TITLE
Track creation/modification for all boxes, products, users, organisations, orders 

### ISSUE THREAD

**Issue by barto74** [boxwise/boxwise#59]
We would like to see creation date and creating user for everything
And a human readable change log for everything
In a user's log I want to see all creations and modifications for that user.

**Comment by HaGuesto** [comment]
@bfirsh I would set up histories in subcollections. Didn't you mention that there might be an easy solution to track all changes?

**Comment by HaGuesto** [comment]
### Questions for tripAdvisor HackDay
How can we track all changes to the Firebase database? Should we track all changes?
How can the history itself be stored in firestore?  
How can we add automaticaly createdAT, createdBY, modifiedAT, modifiedBY to each document in firestore?
