### ISSUE TITLE
Choosing 'number' as type for a Textfield should give a numeric keyboard on an iPhone

### ISSUE THREAD

**Issue by barto74** [boxwise/boxwise#66]
## Problem
In makebox-ui, an numeric field is defined, but on iOS it doesn't show a numeric input keyboard.

**Comment by HaGuesto** [comment]
@barto74 Could this be an issue for the Hackathon?

**Comment by barto74** [comment]
@HaGuesto that depends on the knowledge of the people in the hackaton.

**Comment by HaGuesto** [comment]
Would you like to write it down as a good first issue for the Hackathon or should I do it?

**Comment by bfirsh** [comment]
Tip: we all have the power to edit issues, so I have been editing some of Bart’s to clarify them for good first issues. (Sorry Bart. ;)

**Comment by HaGuesto** [comment]
@barto74 Can you specify this problem a bit more in detail? Does it happen in general in all forms or only in certain cases?

**Comment by barto74** [comment]
@HaGuesto if you have an input field that requires a number to be filled in, the keyboard of your smartphone should not display its default keyboard, but a numeric keypad. I think this is what is needed for that: 
`<input type="text" **pattern="\d***">`
This should be used for any input field that only allows numbers.

**Comment by acournoyer1** [comment]
I'm grabbing this one

**Comment by ageektrapped** [comment]
I don't quite know what do here.

The fix for this is putting `pattern="[0-9]*" inputmode="numeric"` in the `<input />` tag. Just putting this on the <Field> in render puts those attributes on the containing `<div/>`.

Not quite sure how to get it in the input yet.

**Comment by bfirsh** [comment]
D'oh. Yeah this is Material UI being stupid.

Wouldn't `type="number"` work? There is an example of this in the Material UI docs. https://material-ui.com/demos/text-fields/

**Comment by ageektrapped** [comment]
I figured it out. Pull Request is up.

(shrug)

iOS expects more, apparently. I'm not sure why.

**Comment by bfirsh** [comment]
Thanks @ageektrapped!
