### ISSUE TITLE
Component ProductButton: icon and label should be below each other

### ISSUE THREAD

**Issue by barto74** [boxwise/boxwise#74]
Now they are displayed next to each other.

**Comment by HaGuesto** [comment]
@barto74 
I do not fully understand this issue.
Could this be a design task for the Hackathon?

**Comment by barto74** [comment]
@HaGuesto this is a comment to the product/category selector component that i built. It is not yet used at the moment. It is a bit of css work that i didn't manage.

**Comment by HaGuesto** [comment]
Would you like to write it down as a good first issue for the Hackathon or should I do it?
