### ISSUE TITLE
How should we deal with duplicate organization names?

### ISSUE THREAD

**Issue by bfirsh** [boxwise/boxwise#83]
Technically it is not an issue, but it might be confusing for users if there are multiple organizations with the same name. "We're both in the same organization... why are we seeing different boxes?"

**Comment by barto74** [comment]
Would be nice to warn people when they create an organization that already exists. And if they would rather be part of the existing organization, they should be able to enter their (name and) email address and requist to receive an invite from the org's admin account.
Org's admins could be either notified through email or a warning inside the app itself, or both.

**Comment by HaGuesto** [comment]
I would actually make the organization name unique. I am a bit afraid of NGOs who have an account alrady, but lost their credentials and a coordinator went of and they just create a new account,...

**Comment by bfirsh** [comment]
@HaGuesto I am inclined to agree.

**Comment by barto74** [comment]
@HaGuesto @bfirsh i agree too

**Comment by barto74** [comment]
And what can we offer to users that discover that their organization already exists? Like an email with login credentials or something? Otherwise they'd create a new account with a slightly different name without going back to the old account.

**Comment by HaGuesto** [comment]
If the email address is part of the NGO there should be a password reset. 
If not, there should be a contact form to write the coordinator of the NGO to ask to add them.
