### ISSUE TITLE
You should not be able to create a box until you have created products

### ISSUE THREAD

**Issue by barto74** [boxwise/boxwise#90]
## Problem

When you first sign up, there are no products in the system, so you can't create a box. The create box form looks broken because there is nothing in the select menu.

## Proposed solution

If there are no products, you should not be able to create a box. The create box modal should instead display a message telling you to add a product, and link to the products page.

## Future improvements

When you sign it, it should probably guide you through the first steps. It could even have a few suggested products added already.

However, we need the empty data state anyway, in case you delete all your products, so we may as well start with this.

**Comment by mjn** [comment]
[TA] On it

**Comment by bfirsh** [comment]
Thanks @mjn!
