### ISSUE TITLE
On the make a box form, use react-select for product field

### ISSUE THREAD

**Issue by barto74** [boxwise/boxwise#93]
The list of categories and products will be quite long, so react-select enables typing to search.
That would be a good way to be able to postpone making the real visual elements that we have sketched.

**Comment by bfirsh** [comment]
For tomorrow, I will probably switch all the category/product selects to native selects instead of the material UI overlay. That'll make it much easier to skip through a long list on mobile.

Also: they should be ordered!

**Comment by bfirsh** [comment]
@barto74 are you still working on this or shall I pick it up?

**Comment by barto74** [comment]
@bfirsh you should probably take that, will be faster.

**Comment by sforz** [comment]
Taking this one (from TA)

**Comment by sforz** [comment]
Just noting that on this box we show category / product and this would be on the whole category / product string - fine?

**Comment by bfirsh** [comment]
@sforz Yep - same as current select, I think.

**Comment by sforz** [comment]
I did not find the time to finish this one this morning, whoever is going to work on this next might find this link useful though: https://material-ui.com/demos/autocomplete/

**Comment by HaGuesto** [comment]
I'm on this one.

**Comment by HaGuesto** [comment]
@bfirsh could you checkout the branch `93/search_to_select_products`? I'm stuck. The reason is in the last commit message.
