### ISSUE TITLE
Warehouse design: is our app forcing people to sort on number?

### ISSUE THREAD

**Issue by barto74** [boxwise/boxwise#96]
When we did setup a warehouse with the previous version of the app, we sorted our clothes on piles with the same category. All mens t-shirts together. It is basically what everybody does when storing stuff they want to find again.
Later we learned that with a bigger collection of boxes, this doesn't work well. The stack of shirts is full and a second stack on a random other place is created (with the idea 'we'll sort this out later', which never happens).
That's why we decided to generate six-digit randomised box numbers for every box. And all boxes are sorted in areas by number. We did a few stacks of 00-04, a few of 05-09, 10-14, 15-19, 20-24, etc.
Now the amount of boxes in the warehouse is about equally divided over all stacks. Everything is easy to find again.

### Why it is a good idea:
- All stacks/areas in the warehouse are approximately equally full.
- Never ambiguous location for items
- It kind of forces users to use the app to find a box, instead of just walking up to the t-shirts pile and take a few boxes without administrating the action.
- We can develop future smart behaviour into the app, that is aware of keeping fast moving stuff easily accessible. People don't have to think, just accept the box number.

### Why it is a bad idea:
- If the App fails to work, nobody knows where everything is.

### But we want to keep a specific area for food?
- Never just decide to do that while you use the numeric system, as you create an ambiguity. If people don't know about this specific area, the box might end up in the wrong place (as you can put it with the food, but also in the main area). You can leave the food out of the process, but then you miss out on all the statistics about stuff moving in and out. An idea would be to dedicate a specific range of numbers for a category. So if you dedicate '9' to food, all boxes in the food category will end up with a box number starting with 9 (and all the other categories don't use this range). And if the hygiene category gets the range 84-88, those boxes will start with 84,85,86,87,88 or 89 and these numbers will not be used for other categories.

### Why not make the App able to do both numeric and traditional sorting?
- For almost everybody, the numeric system feels a bit difficult and counterintuitive in the beginning, but in the end they are convinced. So if people have the choice, they will often not choose for numeric, while we see that they should. As our users are merely no warehouse professionals, we feel we should steer them into a direction that is the best possible.

### What is the best amount of boxes within every range?
In Drop in the ocean we had 20 piles in the warehouse, each containing about 30 boxes. If you make more piles the risk is that some piles get bigger and others are empty (due to the randomisation). 
If you make too few piles, the amount of boxes in the pile is too big and finding the box takes too much time. Intuitively, i would recommend about 20-40 boxes in each pile, but we might be able to do some calculations on this?

### How can the numeric system be even more smart?
At this moment a 6-digit number is generated. If it already exists, the procedure is being repeated until a new number is found.
- By taking the real number of boxes in any range in the specific location into account, that makes the distribution of boxes on the piles even better.
- By making smart calculations, by assuming that low numbers are closer to the entry/exit for example, and giving fast moving goods a lower number and slow moving goods a higher number. Or by suggesting to put offseason material in a further away location inside the warehouse.

**Comment by barto74** [comment]
@HaGuesto can you please elaborate inside this issue?

**Comment by HaGuesto** [comment]
In general, I agree with what you wrote. 
First,  I will add some bulletpoints to each section and at the end I will leave some general comments:

## Why is it a good idea? 
- Picking boxes will be faster. The location is clearly and you can easily streamline your volunteers through your piles if your picklist is ordered the right way. 
- You will reduce human. A volunteer has to do one workstep less to create a new box. Volunteers do not have to find empty spaces. 

## Why is it a bad idea? 
- In emergency situations you might just want to know where everthing is without consulting a logistic system. 

Remarks:
- I would like to mention that numbered locations do not just have to be a pile. They can be palettes, shelves, tables,.... 
- Please check out #119 for a soffisticated model of the human ID of a box. 
-We are quite far away from a smart number creation. These are nice ideas and I could think of a few models for that,  but I leave it for now.
